repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.3  # Use the latest version available
    hooks:
    -   id: ruff-check
        args: [ --fix ]
        files: src/
    -   id: ruff-format
        files: src/